Documentation
Lfdd/Parser pull request #2
Opened 2021-03-05 14:00 UTC by Lfdd

2021-03-09 05:17 UTC, VladimirShitov reviewed
У тебя хорошо получается писать доки :) Поправь только немного комменты

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +    """Takes a data from an given authors
Обычно класс описывают немного не так. Действиями описывают функции/методы. А у класса пишут общими словами что-то вроде "Класс для загрузки и обработки публикаций авторов eLibrary"

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +    """Takes a data from an given authors
И "the given authors", пожалуй

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +     data_path: WindowsPath
```suggestion
     data_path: Path
```

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +     date_to, date_from: int
Опиши их на разных строках лучше

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +     Attributes
Добавь ещё driver и publications. Укажи, какие методы их заполняют

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +        """Settings for a selenium web driver"""
Важно отражать, что метод меняет значение какого-либо атрибута. Напиши здесь, что он устанавливает атрибут `self.driver`

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +        dates within which search will be processed
А как именно выбираются даты? Включая обе границы или какая-то из них не попадает?

Например, если я введу года 2016 и 2018, у меня войдут 2016, 2017 и 2018 или только 2016 и 2017?

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
>          while date_diff >= 0:
А почему не `for year in range(self.date_from, self.date_to)`? Было бы интуитивнее и меньше кода

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +                print('No more pages left!')
👍🏻

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +        table_cell --> bs4.element.ResultSet
```suggestion
        table_cell : bs4.element.ResultSet
```

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
>      def get_title(table_cell):
```suggestion
    def get_title(table_cell: bs4.element.ResultSet) -> str:
```

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +        """Gets titles from an HTML page
Не со всей страницы, а из одной ячейки с публикацией же

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +        """Gets authors from an HTML page"""
То же, что и выше. Ещё обычно пишут "Get", а не "Gets"

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +        """Gets journal info from an HTML page"""
То же :)

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +        """Creates a way and csv file for processed data"""
Только path, а не way :)

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +        """Creates a way and csv file for processed data"""
Можно вообще про путь не говорить. Просто "Save author's publications to a csv-file". И ниже опиши колонки этого файла

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +        """ Gets trough the html file and saves information from it"""
```suggestion
        """ Get trough the html file and save information from it"""
```

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/types.py
> +    """ Gets rid of unnecessary and
Просто "Класс для хранения информации о публикациях". Первая строчка скорее загадочно звучит, а не вносит ясность :)

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/types.py
> +     Attributes
Всё круто!

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/types.py
>      def __init__(self, title, authors, info, link):
Ещё вот здесь хорошо бы типы пометить
```suggestion
    def __init__(self, title: str, authors: str, info: str, link: str):
```

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/types.py
> +        """ Creates a row with semicolons between an elements """
```suggestion
        """Create a table row with semicolons between the elements"""
```

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/types.py
> +        """ Gets a year in the range from 1900 to 2100 """
О, вот это круто, что ты рамки лет указал

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/types.py
> +        years = re.findall(r'20\d{2}.|19\d{2}.', self.info)
Убери точку, она помешает приводить год к числе и сломает Ване тест

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/types.py
> +        """ Checks if the hashsum is equal"""
Конкретно этот метод не проверяет равенство хэшей, а просто хэширует публикацию

2021-03-09 05:17 UTC, VladimirShitov commented on elibrary_parser/types.py
> +        """ Gets out any similar authors publications
Магические методы (которые окружены двумя подчёркиваниями) в принципе не обязательно документировать. Их назначение описано в документации питона и все понимают, что они делают

Но можно описать особенности реализации у нас. Что публикации считаются равными, если у них совпадает заголовок, авторы, информация и ссылка)

2021-03-09 11:57 UTC, Lfdd commented on elibrary_parser/Parsers.py
> +    """Takes a data from an given authors
Понял, так и напишу
Хах, да. Вечная проблема с артиклями

2021-03-09 12:01 UTC, VladimirShitov commented
> Т.е. теперь пользователю нужно только скачать gekodriver и положить его в папку с парсером, правильно я понимаю?

Можно положить и в другое место, главное - указать путь к драйверу в файле config.py

2021-03-09 12:32 UTC, Lfdd commented on elibrary_parser/Parsers.py
>          while date_diff >= 0:
Не знаю. Могу переписать, конечно

2021-03-09 13:21 UTC, Lfdd commented on elibrary_parser/Parsers.py
> +     Attributes
А в таком случае не нужно указывать методы для всех? Или если писать 
Methods
    -------
Только для этих двух достаточно

2021-03-15 13:12 UTC, VladimirShitov commented on 1_download_publications.py
> +    #parser.save_publications()
Давайте не пушить этот файл в будущем. Будут проблемы со слиянием из-за того, что каждый в нём что-то своё пишет. Лучше вообще удалить, а вместо него сделать какой-нибудь скрипт example.py с примером использования

2021-03-15 13:20 UTC, VladimirShitov requested changes
Укажи ещё типы аргументов и возвращаемые типы методов. Я оставил комменты, как это сделать :)

2021-03-15 13:20 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
> +        table_cell : bs4.element.ResultSet
Описания не хватает :/ И тип нужно прямо в коде указать, а не только в документации

2021-03-15 13:20 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
>      def get_title(table_cell):
Пометил как разрешённое, а код не поправил .-.

2021-03-15 13:20 UTC, VladimirShitov commented on elibrary_parser/types.py
> +        other --> str
other — это не строка, а другая публикация. И подсказка к типу в этом случае указывается через двоеточие

2021-03-15 13:20 UTC, VladimirShitov commented on elibrary_parser/types.py
> +        other --> str
```suggestion
        other : Publication
```

2021-03-15 13:20 UTC, VladimirShitov commented on elibrary_parser/types.py
>      def __eq__(self, other):
```suggestion
    def __eq__(self, other: Publication) -> bool:
```

2021-03-15 13:20 UTC, VladimirShitov commented on elibrary_parser/types.py
> +        ----------------------
Слишком много дефисов: их ставят по количеству символов в слове выше

2021-03-15 13:20 UTC, VladimirShitov commented on elibrary_parser/types.py
> +        """ Hashses a publication"""
```suggestion
        """ Hashes a publication"""
```

2021-03-15 13:20 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
>      def get_info(table_cell):
```suggestion
    def get_info(table_cell: bs4.element.ResultSet) -> str:
```

2021-03-15 13:20 UTC, VladimirShitov commented on elibrary_parser/Parsers.py
>      def get_link(table_cell):
```suggestion
    def get_link(table_cell: bs4.element.ResultSet) -> str:
```

2021-03-15 13:20 UTC, VladimirShitov commented on elibrary_parser/test_author_parser.py
> +    assert AuthorParser.get_title(table_cell) == "-"
О, а как это тут оказалось? Это же из ветки Вани. Будут проблемы со слиянием :/

2021-03-16 15:48 UTC, Lfdd commented on 1_download_publications.py
> +    #parser.save_publications()
Если его сейчас удалить тоже будут проблемы?

2021-03-16 15:50 UTC, VladimirShitov commented on 1_download_publications.py
> +    #parser.save_publications()
Не должно, давай удалим :)

2021-03-16 15:54 UTC, Lfdd commented on elibrary_parser/types.py
> +        ----------------------
А как это высчитывается? У меня везде одно число, вроде

2021-03-16 16:01 UTC, Lfdd commented on elibrary_parser/Parsers.py
> +        table_cell : bs4.element.ResultSet
Ну...Я добавил слово publication, хахах. Не знаю просто что еще можно добавить в описание

2021-03-16 16:12 UTC, VladimirShitov commented on elibrary_parser/types.py
> +        ----------------------
Ну, просто ставишь дефисы, пока не дойдёшь до длины слова :) Типа 
```
Parameters
----------

Returns
-------
```

2021-03-16 16:13 UTC, VladimirShitov approved these changes
Супер! Подождём комментов от Вани и сливаем :)

2021-03-16 16:18 UTC, Lfdd commented on README.md
> -# Парсер научных журналов
Немного схитрил, чтобы не было ругательств при сливании

2021-03-16 16:19 UTC, Lfdd commented on elibrary_parser/types.py
> +        ----------------------
Странно, в статье что ты кидал было их больше. Но я подправил уже

2021-03-16 16:31 UTC, Lfdd reviewed
Не идеально, не особо умно, зато с душой!

2021-03-16 17:38 UTC, IvanZavaruev commented on README.md
> +установить [gekodriver.exe](https://github.com/mozilla/geckodriver/releases),
Не уверен, но разве не стоит указать, что для работы селениума с данным гекодрайвером нужна Мозила ?

2021-03-16 17:39 UTC, IvanZavaruev commented on README.md
> +установить [gekodriver.exe](https://github.com/mozilla/geckodriver/releases),
В остальном , я конечно не эксперт, но все классно )

2021-03-16 17:48 UTC, Lfdd commented on README.md
> +установить [gekodriver.exe](https://github.com/mozilla/geckodriver/releases),
Нет, гекодрайвер сам по себе говорит, что это мозилла. Для хрома движок другой

2021-03-16 17:49 UTC, merged

2021-03-17 05:32 UTC, VladimirShitov commented on README.md
> +установить [gekodriver.exe](https://github.com/mozilla/geckodriver/releases),
Ваня прав, кстати. У меня вылетало с ошибкой, когда не была установлена мобила (хотя гекодрайвер был). Нужен и браузер, и движок